#!/usr/bin/env python3
"""scripts/export_dashboard.py — bundle current v2 dashboard as portable zip.

Output: cache/swingtrade_dashboard_<DATE>_<TIME>.zip
Inside: infra/prototype/ tree (dashboard.html + data.json + tickers.json +
tabs/* + core/*) + a README.txt explaining how to open.

The dashboard runs against the bundled data — fully offline, no server,
no API calls. Use cases: email a snapshot, archive a scan state, share
with a peer, view on a phone.

Skips: backup files (.bak, .broken-*), mockups (_mockup), legacy archives
(_legacy_dashboards), and source-only artifacts.

Usage:
    python3 scripts/export_dashboard.py                 # default: cache/
    python3 scripts/export_dashboard.py --out ~/Desktop # custom out dir
    python3 scripts/export_dashboard.py --include-cache # also bundle cache/last_bundle.json
"""
import argparse
import json
import sys
import zipfile
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PROTO = ROOT / "infra" / "prototype"
DEFAULT_OUT = ROOT / "cache"

# Patterns to skip when bundling
SKIP_FRAGMENTS = (
    ".bak", ".broken-", ".snap-pre-", "_mockup", "_legacy_", "_decision_tree",
    "_settings_roles", "_settings_users", "_tab_visibility",
)

README = """\
SwingTrade Dashboard — Offline Snapshot
=========================================

Generated: {generated}
Scan as-of: {scan_date} {scan_time}
Tickers in this bundle: {ticker_count}
Bundle size: {size_mb:.1f} MB

How to view
-----------
1. Extract this zip to any folder
2. Open `dashboard.html` in a modern browser (Chrome/Safari/Firefox).
   - Some browsers block fetch() from file:// — if the dashboard shows
     "Loading…" forever, run a tiny local server in the extracted folder:
       python3 -m http.server 8000
     then open http://localhost:8000/dashboard.html

What's inside
-------------
  dashboard.html            — main scan dashboard (the v2 UI)
  elite-detail.html         — per-ticker analysis page
  data.json                 — scan-wide state (regime, sectors, perf, etc.)
  data.critical.json        — boot-critical subset
  data_*.json               — lazy chunks (crypto/earnings/killed/perf/...)
  tickers.json              — full per-ticker payloads (~210 fields × N tickers)
  core/*.js                 — ES module shared utilities
  tabs/*/*.js               — per-tab module renderers (CapStudio architecture)

The Fields · Schema tab in particular shows every per-ticker field with
filterable category chips, presets, and a column picker — useful as a
reference even offline.

Generated by scripts/export_dashboard.py
"""


def _should_include(path: Path) -> bool:
    s = str(path)
    if any(frag in s for frag in SKIP_FRAGMENTS):
        return False
    # Skip dotfiles, OS junk
    if path.name.startswith(".") or path.name == ".DS_Store":
        return False
    # Skip Python source — UI is HTML/JS/JSON
    if path.suffix == ".py":
        return False
    return True


def main() -> int:
    p = argparse.ArgumentParser(description="Export v2 dashboard as portable zip")
    p.add_argument("--out", default=str(DEFAULT_OUT),
                   help=f"Output directory (default: {DEFAULT_OUT})")
    p.add_argument("--include-cache", action="store_true",
                   help="Also bundle cache/last_bundle.json (raw scan output, large)")
    args = p.parse_args()

    if not PROTO.exists():
        print(f"ERROR: {PROTO} not found", file=sys.stderr)
        return 1

    out_dir = Path(args.out).expanduser().resolve()
    out_dir.mkdir(parents=True, exist_ok=True)

    now = datetime.now()
    stamp = now.strftime("%Y-%m-%d_%H%M")
    out_path = out_dir / f"swingtrade_dashboard_{stamp}.zip"

    # Gather scan metadata for the README
    scan_date = scan_time = "—"
    ticker_count = 0
    try:
        d = json.loads((PROTO / "data.json").read_text())
        scan_date = d.get("run_date") or scan_date
        rt = d.get("run_timestamp") or ""
        # "2026-05-10 22:23" → "22:23"
        if " " in rt:
            scan_time = rt.split(" ", 1)[1]
        elif rt:
            scan_time = rt
    except Exception:
        pass
    try:
        t = json.loads((PROTO / "tickers.json").read_text())
        ticker_count = len(t) if isinstance(t, dict) else len(list(t))
    except Exception:
        pass

    included = []
    total_bytes = 0
    print(f"[export] Bundling {PROTO} → {out_path}")
    with zipfile.ZipFile(out_path, "w", zipfile.ZIP_DEFLATED, compresslevel=6) as z:
        for f in sorted(PROTO.rglob("*")):
            if not f.is_file():
                continue
            if not _should_include(f):
                continue
            arc = "dashboard/" + str(f.relative_to(PROTO))
            z.write(f, arcname=arc)
            sz = f.stat().st_size
            included.append((arc, sz))
            total_bytes += sz

        if args.include_cache:
            lb = ROOT / "cache" / "last_bundle.json"
            if lb.exists():
                z.write(lb, arcname="dashboard/_raw_last_bundle.json")
                sz = lb.stat().st_size
                included.append(("dashboard/_raw_last_bundle.json", sz))
                total_bytes += sz

        # Insert README
        readme = README.format(
            generated=now.strftime("%Y-%m-%d %H:%M:%S %Z"),
            scan_date=scan_date, scan_time=scan_time,
            ticker_count=ticker_count,
            size_mb=total_bytes / 1024 / 1024,
        )
        z.writestr("dashboard/README.txt", readme)

    zip_size = out_path.stat().st_size
    print(f"[export] Wrote {out_path} ({zip_size / 1024 / 1024:.2f} MB compressed, "
          f"{total_bytes / 1024 / 1024:.2f} MB raw across {len(included)} files)")

    print()
    print("Top 10 largest files:")
    for arc, sz in sorted(included, key=lambda x: -x[1])[:10]:
        print(f"  {sz / 1024:>8.1f} KB  {arc}")

    print()
    print(f"To view: unzip and open dashboard/dashboard.html")
    print(f"If browser blocks file:// fetches, run:")
    print(f"  cd <extracted-dir>/dashboard && python3 -m http.server 8000")
    print(f"  then open http://localhost:8000/dashboard.html")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
