#!/usr/bin/env python3
"""
validate_per_mode_weights.py — Walk-forward validation for Phase-3 per-mode
pillar weights (Option A roadmap, docs/per_mode_decisions_roadmap.md).

Phase 3 shipped INTUITION-BASED weights as an explicit principle-7 override.
This script provides the validation evidence that should have come first:
runs a baseline backtest (current single-set scoring_weights) plus three
mode-weighted backtests (SWING / POSITION / INVESTMENT weights applied
universally), then compares WR / PF / max-DD / Sharpe per mode vs baseline
and emits a pass/fail verdict.

USAGE
─────
  # Smoke mode (~10 min total): 30 days, top-100 universe, portfolio
  python3 scripts/validate_per_mode_weights.py --smoke

  # Full validation (~2-4 hours total): 252d, full universe
  python3 scripts/validate_per_mode_weights.py --full

  # Mid-tier (~30-60 min total): 60d, full universe
  python3 scripts/validate_per_mode_weights.py --days 60

  # Resume from a prior baseline (skip re-running it)
  python3 scripts/validate_per_mode_weights.py --full --baseline-run path/to/baseline.json

  # Custom output directory
  python3 scripts/validate_per_mode_weights.py --smoke --output-dir cache/phase3_validation_smoke

VERDICT CRITERIA
────────────────
Per docs/per_mode_decisions_roadmap.md Phase 3 section:
  Revert (flip per_mode_pillar_reweight._enabled = false) if ANY mode shows:
    profit_factor      ≤ 1.0× baseline   OR
    win_rate           ≤ baseline − 5 pp

If all 3 modes clear those floors, the per-mode weights are at least
non-degrading and may be promoted (still recommended: re-validate on a
longer window before committing to them long-term).

OUTPUT
──────
  <output-dir>/baseline.json
  <output-dir>/swing.json
  <output-dir>/position.json
  <output-dir>/investment.json
  <output-dir>/verdict.md          ← human-readable comparison + verdict
  <output-dir>/verdict.json        ← machine-readable summary
"""
from __future__ import annotations

import argparse
import json
import shutil
import subprocess
import sys
import time
from datetime import datetime
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

# Import the per-mode weight constants so the validation always uses the
# same numbers as production. Single source of truth = analysis.py.
from analysis import _MODE_PILLAR_WEIGHTS  # noqa: E402

# Map _MODE_PILLAR_WEIGHTS keys → scoring_weights keys (config schema).
_PILLAR_KEY_MAP = {
    "trend":        "trend_structure",
    "rs":           "rs_sector",
    "catalyst":     "catalyst_expansion",
    "smart_money":  "smart_money",
    "fundamentals": "quality_fundamentals",
    "entry_rr":     "entry_rr",
}


def _build_scoring_weights(mode: str) -> dict:
    """Convert _MODE_PILLAR_WEIGHTS[mode] (0..1 ratios) to scoring_weights
    dict (raw pillar maxes summing to ~100)."""
    weights = _MODE_PILLAR_WEIGHTS[mode]
    out = {"_note": f"Phase-3 validation · mode={mode} · auto-generated by validate_per_mode_weights.py"}
    for k, v in weights.items():
        out[_PILLAR_KEY_MAP[k]] = round(v * 100, 1)
    return out


def _write_override(path: Path, scoring_weights: dict | None) -> None:
    """Write a config-override JSON. scoring_weights=None → baseline
    (no scoring_weights override, just disable rolling_sharpe_kill for
    consistency across the run)."""
    override: dict = {"rolling_sharpe_kill": {"_enabled": False}}
    if scoring_weights is not None:
        override["scoring_weights"] = scoring_weights
        # Force Phase 3 OFF during baseline+mode-weighted runs — we want to
        # compare the EFFECT of swapping scoring_weights at the legacy
        # composite path, not double-apply Phase-3 reweighting on top.
        override["per_mode_pillar_reweight"] = {"_enabled": False}
    else:
        override["per_mode_pillar_reweight"] = {"_enabled": False}
    path.write_text(json.dumps(override, indent=2))


def _run_backtest(label: str, days: int, min_score: int, universe: str,
                  config_override_path: Path, top_n: int, hold_days: int,
                  output_dir: Path, smoke: bool) -> Path | None:
    """Launch backtest.py as a subprocess. Returns path to the resulting
    portfolio_backtest_*.json (most recent in cache/), or None on failure."""
    log_path = output_dir / f"{label}.log"

    # Snapshot cache/portfolio_backtest_*.json timestamps so we can find
    # the NEW file produced by this run.
    cache_dir = ROOT / "cache"
    before = {p.name for p in cache_dir.glob("portfolio_backtest_*.json")}

    cmd = [
        sys.executable, str(ROOT / "backtest.py"),
        "--days", str(days),
        "--hold", str(hold_days),
        "--min-score", str(min_score),
        "--top-n", str(top_n),
        "--portfolio",
        "--universe", universe,
        "--config-override", str(config_override_path),
        "--accept-low-buys",  # silence the new min_score guard for grid runs
    ]
    if smoke:
        cmd.append("--smoke")
    print(f"  [{label}] launching: {' '.join(cmd[-4:])}")
    print(f"  [{label}] log → {log_path}")
    t_start = time.time()
    with log_path.open("w") as logf:
        rc = subprocess.call(cmd, stdout=logf, stderr=subprocess.STDOUT, cwd=str(ROOT))
    elapsed = time.time() - t_start
    print(f"  [{label}] exit={rc} elapsed={elapsed:.1f}s")
    if rc != 0:
        print(f"  [{label}] FAILED — see {log_path}")
        return None

    after = {p.name for p in cache_dir.glob("portfolio_backtest_*.json")}
    new_files = sorted(after - before, key=lambda n: (cache_dir / n).stat().st_mtime, reverse=True)
    if not new_files:
        # Smoke mode writes to a known path
        smoke_p = cache_dir / "portfolio_backtest.json"
        if smoke_p.exists() and smoke_p.stat().st_mtime > t_start - 5:
            new_files = [smoke_p.name]
        else:
            print(f"  [{label}] no new portfolio_backtest_*.json produced")
            return None

    src = cache_dir / new_files[0]
    dst = output_dir / f"{label}.json"
    shutil.copy2(src, dst)
    print(f"  [{label}] copied {src.name} → {dst.name}")
    return dst


def _summarize(result_path: Path) -> dict:
    """Pull the key metrics from a portfolio_backtest_*.json."""
    if not result_path or not result_path.exists():
        return {"error": "missing result"}
    d = json.loads(result_path.read_text())
    return {
        "total_trades":   d.get("total_trades"),
        "wins":           d.get("wins"),
        "losses":         d.get("losses"),
        "win_rate":       d.get("win_rate"),
        "profit_factor":  d.get("profit_factor"),
        "total_return_pct": d.get("total_return_pct"),
        "total_pnl":      d.get("total_pnl"),
        "max_drawdown_pct": d.get("max_drawdown_pct"),
        "sharpe":         d.get("sharpe"),
        "avg_win_pct":    d.get("avg_win_pct"),
        "avg_loss_pct":   d.get("avg_loss_pct"),
    }


_MIN_TRADES_FOR_VERDICT = 30  # n<30 → INCONCLUSIVE per CLAUDE.md principle 1


def _identical_outputs(baseline: dict, modes: dict[str, dict]) -> bool:
    """Detect the tautology where all 4 runs produced identical metrics
    (same trades, same PF, same WR). This happens at small sample sizes
    when the top picks are weight-robust — PF ratio of 1.00× is
    mathematical identity, NOT degradation."""
    keys = ("total_trades", "win_rate", "profit_factor", "total_return_pct",
            "max_drawdown_pct", "avg_win_pct", "avg_loss_pct")
    base = tuple(baseline.get(k) for k in keys)
    for s in modes.values():
        if "error" in s:
            continue
        if tuple(s.get(k) for k in keys) != base:
            return False
    return True


def _verdict(baseline: dict, modes: dict[str, dict]) -> tuple[str, list[str]]:
    """Apply the principle-7 floor check per docs roadmap.

    Returns ("PASS", []) if all modes clear the floors, or
            ("FAIL", [reasons]) if any mode degrades below floor, or
            ("INCONCLUSIVE", [reasons]) if sample size is too small
                                          (n<30) or all runs produced
                                          identical outputs (tautology).
    """
    base_n  = baseline.get("total_trades") or 0
    base_pf = baseline.get("profit_factor") or 0
    base_wr = baseline.get("win_rate") or 0

    # Sample-size guard — n<30 across the board → can't infer anything
    if base_n < _MIN_TRADES_FOR_VERDICT:
        return ("INCONCLUSIVE", [
            f"baseline n={base_n} < {_MIN_TRADES_FOR_VERDICT} required for verdict",
            f"too few trades to differentiate weight effects",
            f"action: re-run with --days 60 (mid-tier) or --full (252d) for a real verdict",
        ])

    # Identical-output tautology — different weights produced exactly the
    # same picks/PF/WR. Score reweighting was inert at this sample.
    if _identical_outputs(baseline, modes):
        return ("INCONCLUSIVE", [
            "all 4 runs produced identical metrics (PF / WR / trades match exactly)",
            "weight differentiation didn't change the top picks at this window/universe",
            "this is a sample-size artifact, NOT a verdict on the weights",
            "action: re-run with --days 60+ on the full universe to exercise the weights",
        ])

    failures = []
    for mode, s in modes.items():
        if "error" in s:
            failures.append(f"{mode}: backtest run failed — {s['error']}")
            continue
        mpf = s.get("profit_factor") or 0
        mwr = s.get("win_rate") or 0
        pf_ratio = (mpf / base_pf) if base_pf > 0 else None
        wr_delta = mwr - base_wr
        if pf_ratio is not None and pf_ratio < 1.0:
            failures.append(
                f"{mode}: PF {mpf:.2f} vs baseline {base_pf:.2f} → {pf_ratio:.2f}× < 1.0 "
                f"(degrading)"
            )
        if wr_delta <= -5.0:
            failures.append(
                f"{mode}: WR {mwr:.1f}% vs baseline {base_wr:.1f}% → {wr_delta:+.1f}pp ≤ -5pp"
            )
    if failures:
        return ("FAIL", failures)
    return ("PASS", [])


def _render_verdict(args, baseline_sum: dict, mode_sums: dict, status: str,
                    failures: list[str], output_dir: Path) -> None:
    """Write verdict.md + verdict.json with full comparison + recommendation."""
    ts = datetime.now().isoformat(timespec="seconds")
    rows = []
    rows.append("| metric | baseline | SWING | POSITION | INVESTMENT |")
    rows.append("|---|---|---|---|---|")
    for k in ("total_trades", "win_rate", "profit_factor", "total_return_pct",
              "max_drawdown_pct", "sharpe", "avg_win_pct", "avg_loss_pct"):
        cells = []
        for src in (baseline_sum, mode_sums.get("swing", {}),
                    mode_sums.get("position", {}), mode_sums.get("investment", {})):
            v = src.get(k)
            if v is None or "error" in src:
                cells.append("—")
            elif isinstance(v, float):
                cells.append(f"{v:.2f}")
            else:
                cells.append(str(v))
        rows.append("| " + " | ".join([k] + cells) + " |")

    md = [
        f"# Phase-3 per-mode weight validation — {ts}",
        "",
        f"**Status:** {'✅ PASS' if status == 'PASS' else '⛔ FAIL'}",
        "",
        f"- Days: **{args.days}**",
        f"- Min score: **{args.min_score}**",
        f"- Universe: **{args.universe}**",
        f"- Top-N per day: **{args.top_n}**",
        f"- Hold days: **{args.hold}**",
        "",
        "## Per-pillar weights compared",
        "",
        "| Pillar | Baseline (config.scoring_weights) | SWING | POSITION | INVESTMENT |",
        "|---|---|---|---|---|",
    ]
    base_cfg = json.loads((ROOT / "config" / "config.json").read_text())
    base_sw = base_cfg.get("scoring_weights", {})
    for our_key, schema_key in _PILLAR_KEY_MAP.items():
        b = base_sw.get(schema_key, "—")
        s = round(_MODE_PILLAR_WEIGHTS["swing"][our_key] * 100, 1)
        p = round(_MODE_PILLAR_WEIGHTS["position"][our_key] * 100, 1)
        i = round(_MODE_PILLAR_WEIGHTS["investment"][our_key] * 100, 1)
        md.append(f"| {schema_key} | {b} | {s} | {p} | {i} |")

    md += [
        "",
        "## Backtest results",
        "",
        *rows,
        "",
        "## Pass/Fail criteria",
        "",
        "Per `docs/per_mode_decisions_roadmap.md` Phase 3, revert flag if **any** mode shows:",
        "- `profit_factor ≤ 1.0×` baseline  OR",
        "- `win_rate ≤ baseline − 5pp`",
        "",
        "## Verdict",
        "",
    ]
    if status == "PASS":
        md += [
            "✅ **PASS** — all three modes cleared the floors vs baseline.",
            "",
            "Action: keep `per_mode_pillar_reweight._enabled = true` (default). The Phase-3 weights are non-degrading on this window.",
            "",
            "Recommended follow-up: re-run on a longer window (252d) and ideally a true walk-forward (`backtest/walk_forward_v2.py`) before committing to these weights long-term.",
        ]
    elif status == "INCONCLUSIVE":
        md += [
            "⚠ **INCONCLUSIVE** — not enough signal to render a verdict:",
            "",
        ]
        for f in failures:
            md.append(f"- {f}")
        md += [
            "",
            "Action: this is a **sample-size artifact, NOT a fail on the weights**. The current Phase-3 setting (`per_mode_pillar_reweight._enabled = true`) can stay AS-IS pending a real validation run.",
            "",
            "Next step — run a meaningful sample:",
            "",
            "```bash",
            "# Mid-tier (~30-60 min): 60d, full universe",
            "python3 scripts/validate_per_mode_weights.py --days 60",
            "",
            "# Production validation (~2-4 hr): 252d, full universe",
            "python3 scripts/validate_per_mode_weights.py --full",
            "```",
        ]
    else:
        md += [
            "⛔ **FAIL** — at least one mode degraded vs baseline:",
            "",
        ]
        for f in failures:
            md.append(f"- {f}")
        md += [
            "",
            "Action: revert by editing `config/config.json`:",
            "",
            "```json",
            '"per_mode_pillar_reweight": { "_enabled": false }',
            "```",
            "",
            "Or via env override in the next scan. The legacy single-composite scoring will resume immediately.",
        ]

    (output_dir / "verdict.md").write_text("\n".join(md) + "\n")

    # Machine-readable summary
    verdict_json = {
        "ts": ts,
        "status": status,
        "failures": failures,
        "config": {
            "days": args.days, "min_score": args.min_score,
            "universe": args.universe, "top_n": args.top_n,
            "hold_days": args.hold, "smoke": bool(args.smoke),
        },
        "baseline": baseline_sum,
        "modes": mode_sums,
        "weights": {
            "swing": _MODE_PILLAR_WEIGHTS["swing"],
            "position": _MODE_PILLAR_WEIGHTS["position"],
            "investment": _MODE_PILLAR_WEIGHTS["investment"],
        },
    }
    (output_dir / "verdict.json").write_text(json.dumps(verdict_json, indent=2))


def main() -> int:
    ap = argparse.ArgumentParser(
        description="Validate Phase-3 per-mode pillar weights via backtest comparison.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__.split("USAGE")[1] if "USAGE" in (__doc__ or "") else "",
    )
    ap.add_argument("--smoke", action="store_true",
                    help="Fast iteration mode: --days=30, --universe=top100, ~10 min total.")
    ap.add_argument("--full", action="store_true",
                    help="Production validation: --days=252, --universe=sp500_r1000, ~2-4 hr total.")
    ap.add_argument("--days", type=int, default=None,
                    help="Trading-day window (default: 30 smoke / 252 full).")
    ap.add_argument("--min-score", type=int, default=50,
                    help="Min composite score for BUY (default 50 — backtest-safe floor).")
    ap.add_argument("--universe", choices=["sp500_r1000", "top100"], default=None,
                    help="Universe (default: top100 smoke / sp500_r1000 full).")
    ap.add_argument("--top-n", type=int, default=5, help="Max signals per day.")
    ap.add_argument("--hold", type=int, default=5, help="Hold days.")
    ap.add_argument("--baseline-run", type=str, default=None,
                    help="Path to a prior baseline JSON to skip re-running it.")
    ap.add_argument("--skip-modes", type=str, default="",
                    help="Comma-separated modes to skip (swing,position,investment).")
    ap.add_argument("--output-dir", type=str, default=None,
                    help="Output dir (default cache/phase3_validation_<ts>/).")
    args = ap.parse_args()

    # Resolve mode defaults
    if args.smoke and args.full:
        print("ERROR: --smoke and --full are mutually exclusive")
        return 2
    if args.days is None:
        args.days = 30 if args.smoke else 252
    if args.universe is None:
        args.universe = "top100" if args.smoke else "sp500_r1000"

    # Output dir
    if args.output_dir:
        output_dir = Path(args.output_dir)
    else:
        ts = datetime.now().strftime("%Y%m%d_%H%M%S")
        suffix = "smoke" if args.smoke else "full"
        output_dir = ROOT / "cache" / f"phase3_validation_{suffix}_{ts}"
    output_dir.mkdir(parents=True, exist_ok=True)
    print(f"\nOutput dir: {output_dir}")
    print(f"Config: days={args.days} min_score={args.min_score} universe={args.universe} smoke={args.smoke}\n")

    # Write 4 config-overrides
    baseline_override = output_dir / "override_baseline.json"
    _write_override(baseline_override, scoring_weights=None)
    mode_overrides = {}
    for mode in ("swing", "position", "investment"):
        path = output_dir / f"override_{mode}.json"
        _write_override(path, _build_scoring_weights(mode))
        mode_overrides[mode] = path

    # 1. Baseline
    print("══ 1/4 · BASELINE (current config.scoring_weights) ══")
    if args.baseline_run:
        baseline_result = Path(args.baseline_run)
        if not baseline_result.exists():
            print(f"  ERROR: --baseline-run path does not exist: {baseline_result}")
            return 2
        shutil.copy2(baseline_result, output_dir / "baseline.json")
        baseline_result = output_dir / "baseline.json"
        print(f"  reusing: {baseline_result}")
    else:
        baseline_result = _run_backtest(
            "baseline", args.days, args.min_score, args.universe,
            baseline_override, args.top_n, args.hold, output_dir, args.smoke,
        )
        if not baseline_result:
            print("\n⛔ Baseline failed — aborting")
            return 1
    baseline_sum = _summarize(baseline_result)
    print(f"  baseline: PF={baseline_sum.get('profit_factor')} WR={baseline_sum.get('win_rate')}% "
          f"trades={baseline_sum.get('total_trades')}\n")

    # 2-4. Per-mode runs
    skip = {m.strip().lower() for m in args.skip_modes.split(",") if m.strip()}
    mode_sums = {}
    for idx, mode in enumerate(("swing", "position", "investment"), start=2):
        if mode in skip:
            print(f"══ {idx}/4 · {mode.upper()} — skipped via --skip-modes ══")
            mode_sums[mode] = {"error": "skipped"}
            continue
        print(f"══ {idx}/4 · {mode.upper()} weights ══")
        result = _run_backtest(
            mode, args.days, args.min_score, args.universe,
            mode_overrides[mode], args.top_n, args.hold, output_dir, args.smoke,
        )
        if result:
            mode_sums[mode] = _summarize(result)
            print(f"  {mode}: PF={mode_sums[mode].get('profit_factor')} "
                  f"WR={mode_sums[mode].get('win_rate')}% "
                  f"trades={mode_sums[mode].get('total_trades')}\n")
        else:
            mode_sums[mode] = {"error": "backtest run failed"}
            print(f"  {mode}: FAILED\n")

    # Verdict
    print("══ VERDICT ══")
    status, failures = _verdict(baseline_sum, mode_sums)
    _render_verdict(args, baseline_sum, mode_sums, status, failures, output_dir)

    icon = {"PASS": "✅ PASS", "FAIL": "⛔ FAIL", "INCONCLUSIVE": "⚠ INCONCLUSIVE"}.get(status, status)
    print(f"\nStatus: {icon}")
    if failures:
        label = "Reasons" if status == "INCONCLUSIVE" else "Failures"
        print(f"{label}:")
        for f in failures:
            print(f"  - {f}")
    print(f"\nFull verdict: {output_dir}/verdict.md")
    print(f"             {output_dir}/verdict.json\n")

    # Exit code: 0 = PASS or INCONCLUSIVE (no action), 1 = FAIL (revert flag)
    return 0 if status in ("PASS", "INCONCLUSIVE") else 1


if __name__ == "__main__":
    sys.exit(main())
