tunnel: 53303b70-4fbb-45e5-aa28-fcfa9b54be87
credentials-file: /Users/phanirajgarimella/.cloudflared/53303b70-4fbb-45e5-aa28-fcfa9b54be87.json
ingress:
  - hostname: trade.mystockholding.com
    service: http://localhost:7432
  - service: http_status:404
